defaults:
    - dataset: english
    - preprocessing: default
    - model: default

synthesis_list: datasets/english/synthesis_list.json
in_dir: ./
out_dir: ../static/result
checkpoint: checkpoints/model.ckpt-500000.pt
